language: vi

pipeline:
  # - name: WhitespaceTokenizer
  # - name: CRFEntityExtractor
  # - name: EntitySynonymMapper
  # - name: CountVectorsFeaturizer
  #   token_pattern: (?u)\b\w+\b
  # - name: EmbeddingIntentClassifier
  - name: "SpacyNLP"
    model: "model-final_old"
    case_sensitive: false
  - name: "SpacyTokenizer"
  - name: "SpacyFeaturizer"
  - name: "EmbeddingIntentClassifier"
  - name: "CRFEntityExtractor"
  - name: "EntitySynonymMapper"
  - name: CountVectorsFeaturizer
    token_pattern: (?u)\b\w+\b

policies:
  - name: FallbackPolicy
  - name: MemoizationPolicy
  - name: FormPolicy
  - name: MappingPolicy